### ISSUE TITLE
Buttons are reversed.

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/htmldialog-inputbox#10]
Buttons are reversed for normal Windows pattern. (Have no info on what is normal for OSX.)

The normal order follows the left to right naming of the MB constants.
(See [`UI::messagebox`](https://ruby.sketchup.com/UI.html#messagebox-class_method) for listing.)

**Comment by DanRathbun** [comment]
### Moved to it's own Issue [12 : Text for Accept button should be "OK" for `HtmlUI::inputbox` wrapper](https://github.com/SketchUp/htmldialog-inputbox/issues/12)

----

In addition, the button names do not match [`UI::messagebox`](https://ruby.sketchup.com/UI.html#messagebox-class_method) button names ("OK" vs "Accept".)

The `ArgumentParser#get_options_args()` method is used (_usually_) when mimicking [`UI::inputbox`](https://ruby.sketchup.com/UI.html#inputbox-class_method), so it affords an opportunity to override the default as set in `HtmlUI::Inpubox#initialize`.

The definition of the local `options` hash object in `ArgumentParser#get_options_args()`, at about line 84:
```ruby
      # Convert to option hash.
      options = {
        title: arguments[:title],
        accept_button: 'OK', # mimic UI.inputbox
        inputs: [],
      }
```

**Comment by matthes-b** [comment]
I support that the 'Ok' button should be called 'Ok'.

**Comment by thomthom** [comment]
It's on our list to apply Modus to these examples. In which case the primary button is on the right. https://modus.trimble.com/components/modals/#specifications

A PR of customizing the title of the buttons will be accepted.

**Comment by DanRathbun** [comment]
Well, the Modus CSS is **separate** issue which I discussed in passing in [another issue](https://github.com/SketchUp/htmldialog-inputbox/issues/1#issuecomment-409400239) 3 years ago now.

I myself in my edition already replaced the stylesheets will my own. (I and other devs see **no good use** for huge complicated stylesheets like Modus and Bootstrap for an interface a simple as one mimicking [`UI::inpubox`](https://ruby.sketchup.com/UI.html#inputbox-class_method).)

**Enough** of this we can discuss more in the Modus issue #5.

----

**... back on issue topic:**

Thomas, I think that you miss the point here that we have been talking about.  And this is the "rule" whether (or not) the `HtmlUI::inputbox` wrapper method is **meant** to mimic [`UI::inputbox`](https://ruby.sketchup.com/UI.html#inputbox-class_method) in **function**, **behavior** and **appearance**.

Even if you (and your team) do not apply this "rule", @matthes-b makes the point that **he does** and that other coders **may**.

----

So, what I simply said above was that, if the accept button had an "OK" override set in `ArgumentParser#get_options_args()`, at about line 84, then that would **only** apply when the "mimicking" `HtmlUI::inputbox` wrapper method was used.

**It would **not** apply when advanced hash arguments where used.**

As far as button order goes ... devs can use edited html files for their own editions, if they want different order.

**Comment by Eneroth3** [comment]
The button order for Mac is right to left, so this isn't necessarily reversed. Sticking to Modus is probably better than having it be platform dependent.

**Comment by DanRathbun** [comment]
Alrighty then, ... I created another issue for the "OK" button text.
Ie ... Issue [12 : Text for Accept button should be "OK" for `HtmlUI::inputbox` wrapper](https://github.com/SketchUp/htmldialog-inputbox/issues/12)

----

Since it seems there is no desire to change the button order per platform, and it appears that there is a general impetus to promote Trimble Modus UX styling (here and elsewhere,) ... I am closing this issue. (There is no point in debating it further.)

Y'all can label it "Works as intended" if ya' like.

**Comment by thomthom** [comment]
> And this is the "rule" whether (or not) the HtmlUI::inputbox wrapper method is meant to mimic UI::inputbox in function, behavior and appearance.

The intention of this project was to present an `example` of using `UI::HtmlDialog`. Making an "extended" version of `UI.inputbox` makes it relatable, and possible useful. However, it was never intended to be a complete library. And certainly never to mimic the  appearance and UX behaviour of `UI.inputbox`. `UI.inputbox` has a number of problems and quirks, it'd make no sense to replicate that. I wouldn't really encourage the API that mimicks `UI.inputbox`, it was just a very simple wrapper to implement that would let you easily switch from that and this `HtmlDialog` example. In a more polished variant I would probably have made `prompt` return a `Hash` instead of an `Array` so it would be possible to access the result by keys and not positional indicies.

While this example wasn't intended to be more than that, we do see it has sparked interest. So if the community is interested in contributing via pull requests we're happy to consider them.

**Comment by DanRathbun** [comment]
> However, it was never intended to be a complete library.

I noted this in another thread where Matthes and I were discussing the "mimic rule".

> And certainly never to mimic the appearance and UX behaviour of `UI.inputbox`.

Okay. Thank you for the "official" clarification.

I also noted in that other issue that the comments in the code use the phrase "**similar to `UI.inputbox`**".

> `UI.inputbox` has a number of problems and quirks, it'd make no sense to replicate that.

And I said this same thing also and Matthes agreed.

> I wouldn't really encourage the API that mimicks `UI.inputbox` ...

Well, there are devs (Matthes is one) who want it's **behavior** to be the same. Meaning the interaction with the user and how the user moves from field to field, how the dropdowns and listboxes work and what the ENTER key does. I pointed out that this might vary with platform (and I do not have a Mac to test and know how the native inputbox behaves.)

This gets into the old quagmire we had with the deprecated `UI::WebDIalog` and the platform differences. I think I would rather have the input controls on both platforms work the same way as (I think) the W3C specifications would say they should.

----

> In a more polished variant I would probably have made `prompt` return a `Hash` instead of an `Array` so it would be possible to access the result by keys and not positional _indices_.

Yes, I was thinking of this as well. But hadn't gotten to the point of coming up with a solution.
Maybe a constructor boolean argument or perhaps a dedicated "prompt_for_hash" method.
Anyway ... a bit off-topic for this thread.

**EDIT**: I filed what I think is the simplest solution as [Issue 13 : **Utility method to convert results to a hash**](https://github.com/SketchUp/htmldialog-inputbox/issues/13)

----

Anyway .. I closed this issue as it is not worth keeping open and is too much work to implement platform dependent button ordering. Ie ... it wouldn't really bring much to this **example project**.

It might be done with VueJS component files conditionally loaded on demand, but I'll look into that at a later date.
I do **not** want to get into the scenario of having one html file for Mac and another for Windows. That would double the maintenance of the JS and HTML interface.

**Comment by thomthom** [comment]
> Well, there are devs (Matthes is one) who want it's behavior to be the same. Meaning the interaction with the user and how the user moves from field to field, how the dropdowns and listboxes work and what the ENTER key does. I pointed out that this might vary with platform (and I do not have a Mac to test and know how the native inputbox behaves.)

We need to move these discussions away from "because `UI.inputbox` does it" to talking about "why it is an improvement".

For instance, we don't want to adopt how `UI.inputbox` moves between input fields when tabbing, it starts with the focus on the last element and the order isn't even looping around in an ordered manner:

![2021-09-29_11h41_52](https://user-images.githubusercontent.com/192418/135255102-6a651f87-a6b1-4f4d-96c3-d186fbc57a5c.gif)

Replicating `UI.inputbox` 1:1 will never be a goal. But features/behaviour in `UI.inputbox` that was useful and not buggy can off course be adopted here. But we should focus on talking about the reasons why something was good/useful. SketchUp's UI elements and paradigm for the desktop application is very dated, they origin back to version 1, twenty years ago. We're working on rewamping this and to help bring extensions into a more consistent user experience. This means our UI/UX examples going forward will be rooted in [Trimble's Modus design system](https://modus.trimble.com/). When that doesn't cover everything we will be looking to the platform guidelines for references:

* https://docs.microsoft.com/en-us/windows/apps/design/
* https://developer.apple.com/design/human-interface-guidelines/

We have more UX people to consult with these days to help us for projects like this if we should run into scenarios where it's not clear which design option to choose.

**Comment by DanRathbun** [comment]
I never considered bringing the tabbing order over to this repo. That would be silly.

> But features/behaviour in `UI.inputbox` that was useful and not buggy can off course be adopted here.

**Agreed.**

(Comments moved to new issue: [15 : Compatibility shim does not allow 2 args or an empty window caption](https://github.com/SketchUp/htmldialog-inputbox/issues/15).)

**Comment by DanRathbun** [comment]
@thomthom Please copy and paste your Modus comments to the Modus issue thread.
